apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-shopapp-autoscaling
  namespace: shopapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: backend-shopapp-deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
