apiVersion: v1
kind: Secret
metadata:
  name: backend-shopapp-appsetting-json-secret
  namespace: shopapp
type: Opaque
stringData:
  ConnectionStrings__Database: "Server=<db_host>,<db_port>;Database=<db_name>;User Id=<db_username>;Password=<db_password>;TrustServerCertificate=True;"
  ConnectionStrings__Redis: "<redis_host>:<redis_port>,password=<redis_password>"
  Jwt__Key: "<jwt_key>"
  Jwt__Issuer: "<jwt_Issuer>"
  Jwt__Audience: "<jwt_Audience>"
  EmailSettings__SenderName: "ShopApp"
  EmailSettings__SenderEmail: "<email_address>"
  EmailSettings__Password: "<password_password>"
  Vnpay__TmnCode: "<vnpay_TmnCode>"
  Vnpay__HashSecret: "<vnpay_HashSecret>"
  Vnpay__BaseUrl: "<vnpay_BaseUrl>"
  Vnpay__ReturnUrl: "https://<domain_application>/api/v1/payment/vnpay-return"
  ImageUrl: "<domain_images>"
